### PR TITLE
Quick cleanup

### PR DESCRIPTION
**Pull request by dsmurrell**
Hi Isidro

I'm not doing major changes but a bit of moving things around, ignoring things and deleting unneeded things. You can now switch to the branch that I created and pushed to github to review the changes and comment on them before I merge it.

What I did to do this was, git checkout -b quick_cleanup
then everything else as normal
then push with git push origin quick_cleanup

then I come and review it here and if it looks ok then I create a pull request which sends a message to all the contributors saying 'have a look'. They (you) can comment and when they are happy, then the branch can be merged (in this case by the person who owns the branch), but in a bigger project maybe by the person managing the project. Or if we get other collaborators later, one of us might want to do the merge instead of the 'new' person.

Let me know what you think
Cheers
Daniel

### CODE REVIEW

**Comment by isidroc** [comment]
Hi Daniel, Thanks a lot.
I have switched to this branch.
There are many file in the COX example, which are needed, since in the tutorial corresponding to PCM, we show almost all functions.
I will add the examples for the ensemble.
Talk later!

**Comment by dsmurrell** [comment]
Hi Isidro

Don't switch to my branch :)

Make your own branch for your changes... that way it's easy for me to
review and comment on them before they get merged. You can also commit and
push your changes whenever you like without them affecting the master.

Let me know if you have any comments on the changes I made (just some
structure reordering) and then I can go ahead and merge it.

Cheers
Daniel

**Comment by isidroc** [comment]
HI Daniel,

Ok, I thought we were going to share a dev branch.
Yeah, the changes look fine to me.! Thanks!

2014-04-01 9:51 GMT+02:00 Daniel Murrell notifications@github.com:

> Hi Isidro
> 
> Don't switch to my branch :)
> 
> Make your own branch for your changes... that way it's easy for me to
> review and comment on them before they get merged. You can also commit and
> push your changes whenever you like without them affecting the master.
> 
> Let me know if you have any comments on the changes I made (just some
> structure reordering) and then I can go ahead and merge it.
> 
> Cheers
> Daniel
>

**Comment by dsmurrell** [comment]
Oh, sorry. If you want to make changes to what I've done then by all means,
check out my branch and do it :) If you want to code your own things then I
think it's better to have your own branch. At least that's the way my
friend suggests things should work... lets try it and see how it goes?

Ok, I'll merge that branch then.

**Comment by dsmurrell** [comment]
See now that I've merged mine, you can see how many commits behind (mine)
the master you are and how many commits ahead (yours) you are on your
branch.

https://www.dropbox.com/s/dbqk3or4kz8rcyk/Screenshot%202014-04-01%2011.47.13.png

**Comment by isidroc** [comment]
Cool, thanks a lot Daniel.
I am including the ensemble now in the COX dataset.
Will push within a couple of hours;

2014-04-01 12:48 GMT+02:00 Daniel Murrell notifications@github.com:

**Comment by dsmurrell** [comment]
Ok great. When it's in I'll test it on the LogS data.

**Comment by isidroc** [comment]
ok

2014-04-01 13:04 GMT+02:00 Daniel Murrell notifications@github.com:

> Ok great. When it's in I'll test it on the LogS data.
>

**Pull request merged**
